import type { NextPage } from 'next';
import Head from 'next/head';
import Content from '../components/Content/Content';
import Header from '../components/Header/Header';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Collab.Land Token.Gate Demo</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon/favicon.ico" rel="icon" />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/favicon/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon/favicon-16x16.png"
        />
        <link rel="manifest" href="/favicon/site.webmanifest" />
      </Head>

      <main className={styles.main}>
        <Header />
        <Content />
      </main>
      <footer className={styles.footer}>
        <a
          href="https://www.raidguild.org/"
          rel="noopener noreferrer"
          target="_blank"
        >
          Made with ❤️ by your frens at Raid Guild
        </a>
      </footer>
    </div>
  );
};

export default Home;
